import { FolderPlus, Heart, Search } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { TrackRow } from '../components/TrackRow';
import { TrackArtwork } from '../components/TrackArtwork';
import { usePlayer } from '../player/PlayerContext';

export function LibraryPage() {
  const { createPlaylist, library } = usePlayer(); const [open, setOpen] = useState(false); const [name, setName] = useState('');
  return <div className="page collection-page"><header className="content-topbar"><div><span className="eyebrow">YOUR LIBRARY</span><h1>Collection</h1></div><button className="primary-button" onClick={() => setOpen(true)}><FolderPlus size={17} />New playlist</button></header><div className="library-tabs"><Link to="/liked">Liked Songs</Link><Link to="/history">Recently Played</Link><Link to="/albums">Albums</Link><Link to="/artists">Artists</Link></div><section className="shelf"><header className="section-header"><h2>Your playlists</h2></header>{library.customPlaylists.length ? <div className="result-grid">{library.customPlaylists.map((playlist) => <Link key={playlist.id} to={`/playlist/${playlist.id}`} className="result-card"><TrackArtwork src={playlist.image} alt="" size="lg" /><strong>{playlist.name}</strong><span>{playlist.songs.length} songs</span></Link>)}</div> : <Empty icon={<FolderPlus size={28} />} title="No playlists yet" detail="Create a playlist to collect songs you want to keep together." />}</section>{open && <div className="modal-backdrop" role="presentation"><form className="modal" onSubmit={(event) => { event.preventDefault(); if (name.trim()) { createPlaylist(name.trim()); setName(''); setOpen(false); } }}><span className="eyebrow">NEW PLAYLIST</span><h2>Give it a name</h2><input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Playlist name" /><div><button type="button" className="secondary-button" onClick={() => setOpen(false)}>Cancel</button><button className="primary-button">Create playlist</button></div></form></div>}</div>;
}

export function LikedPage() { const { library } = usePlayer(); const favorites = library.favoriteTracks; return <TrackCollection eyebrow="LIKED SONGS" title="Your favorites" tracks={favorites} empty={<Empty icon={<Heart size={28} />} title="No liked songs yet" detail="Tap the heart next to any track to save it here." />} />; }
export function HistoryPage() { const { library } = usePlayer(); return <TrackCollection eyebrow="LISTENING HISTORY" title="Recently played" tracks={library.history} empty={<Empty icon={<Search size={28} />} title="Nothing played yet" detail="Your recently played music will appear here." />} />; }

function TrackCollection({ eyebrow, title, tracks, empty }: { eyebrow: string; title: string; tracks: ReturnType<typeof usePlayer>['library']['history']; empty: ReactNode }) { return <div className="page collection-page"><header className="content-topbar"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div></header>{tracks.length ? <div className="track-table">{tracks.map((track, index) => <TrackRow track={track} index={index} tracks={tracks} key={track.id} />)}</div> : empty}</div>; }
function Empty({ icon, title, detail }: { icon: ReactNode; title: string; detail: string }) { return <section className="empty-state">{icon}<h2>{title}</h2><p>{detail}</p><Link to="/search" className="primary-button">Find music</Link></section>; }

export function SettingsPage() { return <div className="page collection-page"><header className="content-topbar"><div><span className="eyebrow">SETTINGS</span><h1>Preferences</h1></div></header><div className="settings-list">{[['Appearance', 'Dark appearance is always enabled'], ['Playback', 'Autoplay and crossfade are coming soon'], ['Keyboard shortcuts', 'Space play or pause, arrows seek, N next, P previous, M mute, F favorite'], ['Audio quality', 'Quality follows the stream supplied by your provider'], ['Notifications', 'Coming soon'], ['Account', 'You are listening as a guest'], ['Privacy', 'Library data is stored locally on this device'], ['About', 'Sonora Music 1.0']].map(([name, description]) => <button key={name}><span><strong>{name}</strong><small>{description}</small></span><span>›</span></button>)}</div></div>; }

export function SimpleCollection({ title, kind }: { title: string; kind: 'albums' | 'artists' | 'playlists' | 'genres' }) { const { library } = usePlayer(); const items = kind === 'albums' ? library.favoriteAlbums : kind === 'artists' ? library.favoriteArtists : kind === 'playlists' ? [...library.customPlaylists, ...library.favoritePlaylists] : []; return <div className="page collection-page"><header className="content-topbar"><div><span className="eyebrow">LIBRARY</span><h1>{title}</h1></div></header>{items.length ? <div className="result-grid">{items.map((item) => <Link key={item.id} to={`/${kind === 'albums' ? 'album' : kind === 'artists' ? 'artist' : 'playlist'}/${item.id}`} className="result-card"><TrackArtwork src={item.image} alt="" size="lg" className={kind === 'artists' ? 'round-art' : ''} /><strong>{item.name}</strong><span>{kind === 'artists' ? 'Artist' : kind === 'albums' ? 'Album' : `${(item as { songs?: unknown[] }).songs?.length || 0} songs`}</span></Link>)}</div> : <Empty icon={<FolderPlus size={28} />} title={`No saved ${title.toLowerCase()} yet`} detail="Save music to build your collection here." />}</div>; }
