import { GripVertical, Heart, Pencil, Play, Shuffle, Trash2, X } from 'lucide-react';
import { useEffect, useState, type ReactNode } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { musicService } from '../api/music';
import { TrackArtwork } from '../components/TrackArtwork';
import { TrackRow } from '../components/TrackRow';
import { usePlayer } from '../player/PlayerContext';
import type { Album, Playlist, Track } from '../types/music';

type Status<T> = { data?: T; loading: boolean; error?: string };

export function AlbumPage() { const { id = '' } = useParams(); const [status, setStatus] = useState<Status<Album>>({ loading: true }); useEffect(() => { setStatus({ loading: true }); musicService.album(id).then((data) => setStatus({ loading: false, data })).catch(() => setStatus({ loading: false, error: 'Unable to load this album.' })); }, [id]); return <DetailLayout status={status}>{(album) => <AlbumView album={album} />}</DetailLayout>; }

function AlbumView({ album }: { album: Album }) { const { library, play, toggleFavoriteAlbum } = usePlayer(); const tracks = album.songs || []; const liked = library.favoriteAlbumIds.includes(album.id); return <div className="page detail-page"><header className="detail-header"><TrackArtwork src={album.image} alt={`${album.name} artwork`} size="hero" /><div><span className="eyebrow">ALBUM</span><h1>{album.name}</h1><p>{album.artists.map((artist) => <Link key={artist.id} to={`/artist/${artist.id}`}>{artist.name}</Link>)} {album.year ? ` · ${album.year}` : ''} {album.songCount ? ` · ${album.songCount} songs` : ''}</p><div className="detail-actions"><button className="primary-button" onClick={() => tracks[0] && void play(tracks[0], tracks)}><Play size={17} fill="currentColor" />Play</button><button className="secondary-button" onClick={() => tracks.length && void play(tracks[Math.floor(Math.random() * tracks.length)], tracks)}><Shuffle size={17} />Shuffle</button><button className={`icon-button ${liked ? 'is-active' : ''}`} onClick={() => toggleFavoriteAlbum(album)} aria-label="Like album"><Heart size={18} fill={liked ? 'currentColor' : 'none'} /></button></div></div></header><TrackTable tracks={tracks} /></div>; }

export function ArtistPage() { const { id = '' } = useParams(); const [status, setStatus] = useState<Status<{ artist: { id: string; name: string; image?: string; bio?: string }; tracks: Track[]; albums: Album[] }>>({ loading: true }); useEffect(() => { setStatus({ loading: true }); musicService.artistDetails(id).then((data) => setStatus({ loading: false, data })).catch(() => setStatus({ loading: false, error: 'Unable to load this artist.' })); }, [id]); return <DetailLayout status={status}>{(data) => <ArtistView {...data} />}</DetailLayout>; }
function ArtistView({ artist, tracks, albums }: { artist: { id: string; name: string; image?: string; bio?: string }; tracks: Track[]; albums: Album[] }) { const { library, play, toggleFavoriteArtist } = usePlayer(); const followed = library.favoriteArtistIds.includes(artist.id); return <div className="page detail-page"><header className="artist-header"><TrackArtwork src={artist.image} alt={`${artist.name} portrait`} size="hero" className="round-art" /><div><span className="eyebrow">ARTIST</span><h1>{artist.name}</h1>{artist.bio && <p>{artist.bio}</p>}<div className="detail-actions"><button className="primary-button" onClick={() => tracks[0] && void play(tracks[0], tracks)}><Play size={17} fill="currentColor" />Play</button><button className="secondary-button" onClick={() => toggleFavoriteArtist(artist)}>{followed ? 'Following' : 'Follow'}</button></div></div></header><ArtistTracks tracks={tracks} /><section className="shelf"><header className="section-header"><h2>Albums</h2></header><div className="result-grid">{albums.map((album) => <Link key={album.id} to={`/album/${album.id}`} className="result-card"><TrackArtwork src={album.image} alt="" size="lg" /><strong>{album.name}</strong><span>{album.year || 'Album'}</span></Link>)}</div></section></div>; }
function ArtistTracks({ tracks }: { tracks: Track[] }) { const { play } = usePlayer(); return <section className="shelf"><header className="section-header"><h2>Popular songs</h2></header>{tracks.length ? <><button className="primary-button small" onClick={() => void play(tracks[0], tracks)}><Play size={15} fill="currentColor" />Play popular</button><TrackTable tracks={tracks} /></> : <p className="muted-copy">No popular songs are available.</p>}</section>; }

export function PlaylistPage() { const { id = '' } = useParams(); const { library } = usePlayer(); const custom = library.customPlaylists.find((item) => item.id === id); const [status, setStatus] = useState<Status<Playlist>>({ loading: !custom, data: custom }); useEffect(() => { if (custom) { setStatus({ loading: false, data: custom }); return; } setStatus({ loading: true }); musicService.playlist(id).then((data) => setStatus({ loading: false, data })).catch(() => setStatus({ loading: false, error: 'Unable to load this playlist.' })); }, [custom, id]); return <DetailLayout status={status}>{(playlist) => <PlaylistView playlist={playlist} editable={Boolean(custom)} />}</DetailLayout>; }
function PlaylistView({ playlist, editable }: { playlist: Playlist; editable: boolean }) {
  const navigate = useNavigate();
  const { library, play, removeFromPlaylist, reorderPlaylist, renamePlaylist, deletePlaylist, toggleFavoritePlaylist } = usePlayer();
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState(playlist.name);
  const [description, setDescription] = useState(playlist.description || '');
  const liked = library.favoritePlaylistIds.includes(playlist.id);
  const save = () => { if (name.trim()) { renamePlaylist(playlist.id, name.trim(), description.trim()); setEditing(false); } };
  return <div className="page detail-page"><header className="detail-header"><TrackArtwork src={playlist.image} alt={`${playlist.name} artwork`} size="hero" /><div><span className="eyebrow">PLAYLIST</span><h1>{playlist.name}</h1><p>{playlist.description || 'A collection made for repeat listening.'}</p><p className="muted-copy">{playlist.songs.length || playlist.songCount || 0} songs</p><div className="detail-actions"><button className="primary-button" onClick={() => playlist.songs[0] && void play(playlist.songs[0], playlist.songs)}><Play size={17} fill="currentColor" />Play</button><button className="secondary-button" onClick={() => playlist.songs.length && void play(playlist.songs[Math.floor(Math.random() * playlist.songs.length)], playlist.songs)}><Shuffle size={17} />Shuffle</button><button className={`icon-button ${liked ? 'is-active' : ''}`} onClick={() => toggleFavoritePlaylist(playlist)} aria-label="Like playlist"><Heart size={18} fill={liked ? 'currentColor' : 'none'} /></button>{editable && <><button className="icon-button" onClick={() => setEditing(true)} aria-label="Edit playlist"><Pencil size={17} /></button><button className="icon-button" onClick={() => { if (window.confirm('Delete this playlist?')) { deletePlaylist(playlist.id); navigate('/library'); } }} aria-label="Delete playlist"><Trash2 size={17} /></button></>}</div></div></header>{editable ? <EditablePlaylistTracks playlist={playlist} onRemove={removeFromPlaylist} onReorder={reorderPlaylist} /> : <TrackTable tracks={playlist.songs} />}{editing && <div className="modal-backdrop"><form className="modal" onSubmit={(event) => { event.preventDefault(); save(); }}><span className="eyebrow">EDIT PLAYLIST</span><h2>Refine your playlist</h2><input value={name} onChange={(event) => setName(event.target.value)} aria-label="Playlist name" /><input value={description} onChange={(event) => setDescription(event.target.value)} aria-label="Playlist description" placeholder="Description" /><div><button type="button" className="secondary-button" onClick={() => setEditing(false)}>Cancel</button><button className="primary-button">Save changes</button></div></form></div>}</div>;
}

function EditablePlaylistTracks({ playlist, onRemove, onReorder }: { playlist: Playlist; onRemove: (playlistId: string, trackId: string) => void; onReorder: (playlistId: string, from: number, to: number) => void }) { const [dragIndex, setDragIndex] = useState<number | null>(null); return <section className="track-table-section"><div className="editable-note">Drag tracks to reorder your playlist.</div><div className="track-table">{playlist.songs.map((track, index) => <div className="editable-track" key={track.id} draggable onDragStart={() => setDragIndex(index)} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (dragIndex !== null && dragIndex !== index) onReorder(playlist.id, dragIndex, index); setDragIndex(null); }}><GripVertical className="grab" size={17} /><TrackRow track={track} index={index} tracks={playlist.songs} /><button className="icon-button compact" onClick={() => onRemove(playlist.id, track.id)} aria-label={`Remove ${track.title}`}><X size={16} /></button></div>)}</div></section>; }

export function SongPage() { const { id = '' } = useParams(); const [status, setStatus] = useState<Status<Track>>({ loading: true }); useEffect(() => { setStatus({ loading: true }); musicService.song(id).then((data) => setStatus({ loading: false, data })).catch(() => setStatus({ loading: false, error: 'This track is unavailable.' })); }, [id]); return <DetailLayout status={status}>{(track) => <div className="page detail-page song-page"><header className="detail-header"><TrackArtwork src={track.image} alt={`${track.title} artwork`} size="hero" /><div><span className="eyebrow">TRACK</span><h1>{track.title}</h1><p>{track.artists.map((artist) => artist.name).join(', ')}</p><div className="detail-actions"><SongPlay track={track} /></div></div></header><section className="lyrics-panel"><span className="eyebrow">LYRICS</span><h2>{track.hasLyrics ? 'Lyrics support is not connected yet.' : "Lyrics aren't available for this track."}</h2><p>{track.hasLyrics ? 'The current API response indicates lyric availability, but does not provide lyric text or timing.' : 'We do not invent missing lyric content.'}</p></section></div>}</DetailLayout>; }
function SongPlay({ track }: { track: Track }) { const { play } = usePlayer(); return <button className="primary-button" onClick={() => void play(track)}><Play size={17} fill="currentColor" />Play</button>; }
function TrackTable({ tracks }: { tracks: Track[] }) { return <section className="track-table-section">{tracks.length ? <div className="track-table">{tracks.map((track, index) => <TrackRow key={track.id} track={track} index={index} tracks={tracks} />)}</div> : <div className="empty-state"><h2>No tracks available</h2><p>This item is missing a track listing from the API.</p></div>}</section>; }
function DetailLayout<T>({ status, children }: { status: Status<T>; children: (data: T) => ReactNode }) { if (status.loading) return <div className="page detail-page"><div className="detail-skeleton"><div className="skeleton square" /><div><span className="skeleton-line wide" /><span className="skeleton-line medium" /></div></div></div>; if (status.error || !status.data) return <div className="page-state"><h1>Unable to load this page</h1><p>{status.error || 'Something went wrong.'}</p><Link className="primary-button" to="/">Go Home</Link></div>; return <>{children(status.data)}</>; }
